version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: docker build
          command: docker build -t qmk_firmware .
      - run:
          name: docker run
          command: docker run -e keymap=mine -e keyboard=ergodox_ez --rm -v $('pwd'):/qmk:rw -t qmk_firmware
      - store_artifacts:
          path: .build/ergodox_ez_mine.hex
